### PR TITLE
Support contexts

### PR DESCRIPTION
**Pull request by arnaud-lb**
Implements #32

At the API level, this adds:

 * BackOffContext interface: A BackOff that also supports contexts
 * WithContext(BackOff, context.Context): Returns a BackOffContext from a BackOff

Retry() and Ticker still accept BackOff implementations, but also support BackOffContext implementations.

### CODE REVIEW

**Comment by arnaud-lb** [comment]
This also breaks the compatibility with older Go versions which don't have the context package.

If you want to maintain the compatibility, we should be able to support older Go versions by declaring a backoff.Context interface, and accepting anything that satisfies this interface:

```
type Context interface {
 	Deadline() (deadline time.Time, ok bool)
 	Done() <-chan struct{}
 	Err() error
 	Value(key interface{}) interface{}
 }
```

**Comment by arnaud-lb** [comment]
Added support for older Go versions: 4af6cef9520a4775889714ed23bc82b2dca33d80.

This defines a local version of the Context interface that is satisfied by both "context" and "golang.org/x/net/context" packages. The package then uses "golang.org/x/net/context" where it is necessary to create context instances.

This makes the package compatible with all Go versions supported by "golang.org/x/net/context". It's also compatible with both "context" and "golang.org/x/net/context" packages (it was before, already).

**Comment by arnaud-lb** [comment]
Added support for older Go versions:.

This depends on "golang.org/x/net/context" instead of "context", as the former is always available.

This makes the package compatible with all Go versions supported by "golang.org/x/net/context". 

It's still compatible with both "context" and "golang.org/x/net/context" packages.

**Comment by cenkalti** [comment]
@arnaud-lb Sorry for the delay, I was quite busy this week. I still couldn't review this. I will do it as soon as possible.

**Comment by metalmatze** [comment]
Is there any particular reason not to use the, in Go 1.7 introduced, context from the stdlib?
Do you want to be backwards compatible to 1.3, as it's defined in `.travis.yml`?

**Comment by cenkalti** [comment]
@metalmatze see #40

**Pull request merged**
